DefaultHeader =[
	{
	name: '---',
	sub: [
			{
			name: 'Don\'t include',
			value: 0
			}
		]
	},
	{
	name: 'Person',
	sub: [
			{name: 'First Name', value: 'first'},
			{name: 'Last Name', value: 'last'},
		]
	},
	{
	name: 'Company',
	sub:[
			{name: 'Company Name', value: 'company'},
			{name: 'Acc. Number', value: 'account_no'},
	]
	},
	{
	name: 'Contact',
	sub: [
			{name: 'Email Address', value: 'email'},
			{name: 'Link', value: 'link'},
			{name: 'Mobile No.', value: 'mobile_number'}
		]
	},
	{
	name: 'Address',
	sub: [
			{name: 'Street Address', value: 'address'},
			{name: 'Country', value: 'country'},
			{name: 'City', value: 'city'},
			{name: 'State', value: 'state'}
		]
	},
	{
	name: 'Language',
	sub: [
			{name: 'Language', value: 'language'}
		]
	}

];

LanguageCodes = [
	{name: 'Abkhazian',  code: 'ab'},
	{name: 'Afar',  code: 'aa'},
	{name: 'Afrikaans',  code: 'af'},
	{name: 'Albanian',  code: 'sq'},
	{name: 'Amharic',  code: 'am'},
	{name: 'Arabic',  code: 'ar'},
	{name: 'Aragonese',  code: 'an'},
	{name: 'Armenian',  code: 'hy'},
	{name: 'Assamese',  code: 'as'},
	{name: 'Aymara',  code: 'ay'},
	{name: 'Azerbaijani',  code: 'az'},
	{name: 'Bashkir',  code: 'ba'},
	{name: 'Basque',  code: 'eu'},
	{name: 'Bengali (Bangla)',  code: 'bn'},
	{name: 'Bhutani',  code: 'dz'},
	{name: 'Bihari',  code: 'bh'},
	{name: 'Bislama',  code: 'bi'},
	{name: 'Breton',  code: 'br'},
	{name: 'Bulgarian',  code: 'bg'},
	{name: 'Burmese',  code: 'my'},
	{name: 'Byelorussian (Belarusian)',  code: 'be'},
	{name: 'Cambodian',  code: 'km'},
	{name: 'Catalan',  code: 'ca'},
	{name: 'Chinese',  code: 'zh'},
	{name: 'Chinese (Simplified)',  code: 'zh-Hans'},
	{name: 'Chinese (Traditional)',  code: 'zh-Hant'},
	{name: 'Corsican',  code: 'co'},
	{name: 'Croatian',  code: 'hr'},
	{name: 'Czech',  code: 'cs'},
	{name: 'Danish',  code: 'da'},
	{name: 'Dutch',  code: 'nl'},
	{name: 'English',  code: 'en'},
	{name: 'Esperanto',  code: 'eo'},
	{name: 'Estonian',  code: 'et'},
	{name: 'Faeroese',  code: 'fo'},
	{name: 'Farsi',  code: 'fa'},
	{name: 'Fiji',  code: 'fj'},
	{name: 'Finnish',  code: 'fi'},
	{name: 'French',  code: 'fr'},
	{name: 'Frisian',  code: 'fy'},
	{name: 'Galician',  code: 'gl'},
	{name: 'Gaelic (Scottish)',  code: 'gd'},
	{name: 'Gaelic (Manx)',  code: 'gv'},
	{name: 'Georgian',  code: 'ka'},
	{name: 'German',  code: 'de'},
	{name: 'Greek',  code: 'el'},
	{name: 'Greenlandic',  code: 'kl'},
	{name: 'Guarani',  code: 'gn'},
	{name: 'Gujarati',  code: 'gu'},
	{name: 'Haitian Creole',  code: 'ht'},
	{name: 'Hausa',  code: 'ha'},
	{name: 'Hebrew',  code: 'he'},
	{name: 'Hindi',  code: 'hi'},
	{name: 'Hungarian',  code: 'hu'},
	{name: 'Icelandic',  code: 'is'},
	{name: 'Ido',  code: 'io'},
	{name: 'Indonesian',  code: 'id'},
	{name: 'Interlingua',  code: 'ia'},
	{name: 'Interlingue',  code: 'ie'},
	{name: 'Inuktitut',  code: 'iu'},
	{name: 'Inupiak',  code: 'ik'},
	{name: 'Irish',  code: 'ga'},
	{name: 'Italian',  code: 'it'},
	{name: 'Japanese',  code: 'ja'},
	{name: 'Javanese',  code: 'jv'},
	{name: 'Kannada',  code: 'kn'},
	{name: 'Kashmiri',  code: 'ks'},
	{name: 'Kazakh',  code: 'kk'},
	{name: 'Kinyarwanda (Ruanda)',  code: 'rw'},
	{name: 'Kirghiz',  code: 'ky'},
	{name: 'Kirundi (Rundi)',  code: 'rn'},
	{name: 'Korean',  code: 'ko'},
	{name: 'Kurdish',  code: 'ku'},
	{name: 'Laothian',  code: 'lo'},
	{name: 'Latin',  code: 'la'},
	{name: 'Latvian (Lettish)',  code: 'lv'},
	{name: 'Limburgish ( Limburger)',  code: 'li'},
	{name: 'Lingala',  code: 'ln'},
	{name: 'Lithuanian',  code: 'lt'},
	{name: 'Macedonian',  code: 'mk'},
	{name: 'Malagasy',  code: 'mg'},
	{name: 'Malay',  code: 'ms'},
	{name: 'Malayalam',  code: 'ml'},
	{name: 'Maltese',  code: 'mt'},
	{name: 'Maori',  code: 'mi'},
	{name: 'Marathi',  code: 'mr'},
	{name: 'Moldavian',  code: 'mo'},
	{name: 'Mongolian',  code: 'mn'},
	{name: 'Nauru',  code: 'na'},
	{name: 'Nepali',  code: 'ne'},
	{name: 'Norwegian',  code: 'no'},
	{name: 'Occitan',  code: 'oc'},
	{name: 'Oriya',  code: 'or'},
	{name: 'Oromo (Afaan Oromo)',  code: 'om'},
	{name: 'Pashto (Pushto)',  code: 'ps'},
	{name: 'Polish',  code: 'pl'},
	{name: 'Portuguese',  code: 'pt'},
	{name: 'Punjabi',  code: 'pa'},
	{name: 'Quechua',  code: 'qu'},
	{name: 'Rhaeto-Romance',  code: 'rm'},
	{name: 'Romanian',  code: 'ro'},
	{name: 'Russian',  code: 'ru'},
	{name: 'Samoan',  code: 'sm'},
	{name: 'Sangro',  code: 'sg'},
	{name: 'Sanskrit',  code: 'sa'},
	{name: 'Serbian',  code: 'sr'},
	{name: 'Serbo-Croatian',  code: 'sh'},
	{name: 'Sesotho',  code: 'st'},
	{name: 'Setswana',  code: 'tn'},
	{name: 'Shona',  code: 'sn'},
	{name: 'Sichuan Yi',  code: 'ii'},
	{name: 'Sindhi',  code: 'sd'},
	{name: 'Sinhalese',  code: 'si'},
	{name: 'Siswati',  code: 'ss'},
	{name: 'Slovak',  code: 'sk'},
	{name: 'Slovenian',  code: 'sl'},
	{name: 'Somali',  code: 'so'},
	{name: 'Spanish',  code: 'es'},
	{name: 'Sundanese',  code: 'su'},
	{name: 'Swahili (Kiswahili)',  code: 'sw'},
	{name: 'Swedish',  code: 'sv'},
	{name: 'Tagalog',  code: 'tl'},
	{name: 'Tajik',  code: 'tg'},
	{name: 'Tamil',  code: 'ta'},
	{name: 'Tatar',  code: 'tt'},
	{name: 'Telugu',  code: 'te'},
	{name: 'Thai',  code: 'th'},
	{name: 'Tibetan',  code: 'bo'},
	{name: 'Tigrinya',  code: 'ti'},
	{name: 'Tonga',  code: 'to'},
	{name: 'Tsonga',  code: 'ts'},
	{name: 'Turkish',  code: 'tr'},
	{name: 'Turkmen',  code: 'tk'},
	{name: 'Twi',  code: 'tw'},
	{name: 'Uighur',  code: 'ug'},
	{name: 'Ukrainian',  code: 'uk'},
	{name: 'Urdu',  code: 'ur'},
	{name: 'Uzbek',  code: 'uz'},
	{name: 'Vietnamese',  code: 'vi'},
	{name: 'VolapŸk',  code: 'vo'},
	{name: 'Wallon',  code: 'wa'},
	{name: 'Welsh',  code: 'cy'},
	{name: 'Wolof',  code: 'wo'},
	{name: 'Xhosa',  code: 'xh'},
	{name: 'Yiddish',  code: 'yi'},
	{name: 'Yoruba',  code: 'yo'},
	{name: 'Zulu',  code: 'zu'},
];
CountryCodes = [
	{code: 'AF', name: 'Afghanistan'},
	{code: 'AX', name: 'Aland Islands'},
	{code: 'AL', name: 'Albania'},
	{code: 'DZ', name: 'Algeria'},
	{code: 'AS', name: 'American Samoa'},
	{code: 'AD', name: 'Andorra'},
	{code: 'AO', name: 'Angola'},
	{code: 'AI', name: 'Anguilla'},
	{code: 'AQ', name: 'Antarctica'},
	{code: 'AG', name: 'Antigua and Barbuda'},
	{code: 'AR', name: 'Argentina'},
	{code: 'AM', name: 'Armenia'},
	{code: 'AW', name: 'Aruba'},
	{code: 'AU', name: 'Australia'},
	{code: 'AT', name: 'Austria'},
	{code: 'AZ', name: 'Azerbaijan'},
	{code: 'BS', name: 'Bahamas'},
	{code: 'BH', name: 'Bahrain'},
	{code: 'BD', name: 'Bangladesh'},
	{code: 'BB', name: 'Barbados'},
	{code: 'BY', name: 'Belarus'},
	{code: 'BE', name: 'Belgium'},
	{code: 'BZ', name: 'Belize'},
	{code: 'BJ', name: 'Benin'},
	{code: 'BM', name: 'Bermuda'},
	{code: 'BT', name: 'Bhutan'},
	{code: 'BO', name: 'Bolivia'},
	{code: 'BA', name: 'Bosnia and Herzegovina'},
	{code: 'BW', name: 'Botswana'},
	{code: 'BV', name: 'Bouvet Island'},
	{code: 'BR', name: 'Brazil'},
	{code: 'IO', name: 'British Indian Ocean Territory'},
	{code: 'BN', name: 'Brunei Darussalam'},
	{code: 'BG', name: 'Bulgaria'},
	{code: 'BF', name: 'Burkina Faso'},
	{code: 'BI', name: 'Burundi'},
	{code: 'KH', name: 'Cambodia'},
	{code: 'CM', name: 'Cameroon'},
	{code: 'CA', name: 'Canada'},
	{code: 'CV', name: 'Cape Verde'},
	{code: 'KY', name: 'Cayman Islands'},
	{code: 'CF', name: 'Central African Republic'},
	{code: 'TD', name: 'Chad'},
	{code: 'CL', name: 'Chile'},
	{code: 'CN', name: 'China'},
	{code: 'CX', name: 'Christmas Island'},
	{code: 'CC', name: 'Cocos (Keeling) Islands'},
	{code: 'CO', name: 'Colombia'},
	{code: 'KM', name: 'Comoros'},
	{code: 'CG', name: 'Congo'},
	{code: 'CD', name: 'Congo, The Democratic Republic of The'},
	{code: 'CK', name: 'Cook Islands'},
	{code: 'CR', name: 'Costa Rica'},
	{code: 'CI', name: 'Cote D\'ivoire'},
	{code: 'HR', name: 'Croatia'},
	{code: 'CU', name: 'Cuba'},
	{code: 'CY', name: 'Cyprus'},
	{code: 'CZ', name: 'Czech Republic'},
	{code: 'DK', name: 'Denmark'},
	{code: 'DJ', name: 'Djibouti'},
	{code: 'DM', name: 'Dominica'},
	{code: 'DO', name: 'Dominican Republic'},
	{code: 'EC', name: 'Ecuador'},
	{code: 'EG', name: 'Egypt'},
	{code: 'SV', name: 'El Salvador'},
	{code: 'GQ', name: 'Equatorial Guinea'},
	{code: 'ER', name: 'Eritrea'},
	{code: 'EE', name: 'Estonia'},
	{code: 'ET', name: 'Ethiopia'},
	{code: 'FK', name: 'Falkland Islands (Malvinas)'},
	{code: 'FO', name: 'Faroe Islands'},
	{code: 'FJ', name: 'Fiji'},
	{code: 'FI', name: 'Finland'},
	{code: 'FR', name: 'France'},
	{code: 'GF', name: 'French Guiana'},
	{code: 'PF', name: 'French Polynesia'},
	{code: 'TF', name: 'French Southern Territories'},
	{code: 'GA', name: 'Gabon'},
	{code: 'GM', name: 'Gambia'},
	{code: 'GE', name: 'Georgia'},
	{code: 'DE', name: 'Germany'},
	{code: 'GH', name: 'Ghana'},
	{code: 'GI', name: 'Gibraltar'},
	{code: 'GR', name: 'Greece'},
	{code: 'GL', name: 'Greenland'},
	{code: 'GD', name: 'Grenada'},
	{code: 'GP', name: 'Guadeloupe'},
	{code: 'GU', name: 'Guam'},
	{code: 'GT', name: 'Guatemala'},
	{code: 'GG', name: 'Guernsey'},
	{code: 'GN', name: 'Guinea'},
	{code: 'GW', name: 'Guinea-bissau'},
	{code: 'GY', name: 'Guyana'},
	{code: 'HT', name: 'Haiti'},
	{code: 'HM', name: 'Heard Island and Mcdonald Islands'},
	{code: 'VA', name: 'Holy See (Vatican City State)'},
	{code: 'HN', name: 'Honduras'},
	{code: 'HK', name: 'Hong Kong'},
	{code: 'HU', name: 'Hungary'},
	{code: 'IS', name: 'Iceland'},
	{code: 'IN', name: 'India'},
	{code: 'ID', name: 'Indonesia'},
	{code: 'IR', name: 'Iran, Islamic Republic of'},
	{code: 'IQ', name: 'Iraq'},
	{code: 'IE', name: 'Ireland'},
	{code: 'IM', name: 'Isle of Man'},
	{code: 'IL', name: 'Israel'},
	{code: 'IT', name: 'Italy'},
	{code: 'JM', name: 'Jamaica'},
	{code: 'JP', name: 'Japan'},
	{code: 'JE', name: 'Jersey'},
	{code: 'JO', name: 'Jordan'},
	{code: 'KZ', name: 'Kazakhstan'},
	{code: 'KE', name: 'Kenya'},
	{code: 'KI', name: 'Kiribati'},
	{code: 'KP', name: 'Korea, Democratic People\'s Republic of'},
	{code: 'KR', name: 'Korea, Republic of'},
	{code: 'KW', name: 'Kuwait'},
	{code: 'KG', name: 'Kyrgyzstan'},
	{code: 'LA', name: 'Lao People\'s Democratic Republic'},
	{code: 'LV', name: 'Latvia'},
	{code: 'LB', name: 'Lebanon'},
	{code: 'LS', name: 'Lesotho'},
	{code: 'LR', name: 'Liberia'},
	{code: 'LY', name: 'Libyan Arab Jamahiriya'},
	{code: 'LI', name: 'Liechtenstein'},
	{code: 'LT', name: 'Lithuania'},
	{code: 'LU', name: 'Luxembourg'},
	{code: 'MO', name: 'Macao'},
	{code: 'MK', name: 'Macedonia, The Former Yugoslav Republic of'},
	{code: 'MG', name: 'Madagascar'},
	{code: 'MW', name: 'Malawi'},
	{code: 'MY', name: 'Malaysia'},
	{code: 'MV', name: 'Maldives'},
	{code: 'ML', name: 'Mali'},
	{code: 'MT', name: 'Malta'},
	{code: 'MH', name: 'Marshall Islands'},
	{code: 'MQ', name: 'Martinique'},
	{code: 'MR', name: 'Mauritania'},
	{code: 'MU', name: 'Mauritius'},
	{code: 'YT', name: 'Mayotte'},
	{code: 'MX', name: 'Mexico'},
	{code: 'FM', name: 'Micronesia, Federated States of'},
	{code: 'MD', name: 'Moldova, Republic of'},
	{code: 'MC', name: 'Monaco'},
	{code: 'MN', name: 'Mongolia'},
	{code: 'ME', name: 'Montenegro'},
	{code: 'MS', name: 'Montserrat'},
	{code: 'MA', name: 'Morocco'},
	{code: 'MZ', name: 'Mozambique'},
	{code: 'MM', name: 'Myanmar'},
	{code: 'NA', name: 'Namibia'},
	{code: 'NR', name: 'Nauru'},
	{code: 'NP', name: 'Nepal'},
	{code: 'NL', name: 'Netherlands'},
	{code: 'AN', name: 'Netherlands Antilles'},
	{code: 'NC', name: 'New Caledonia'},
	{code: 'NZ', name: 'New Zealand'},
	{code: 'NI', name: 'Nicaragua'},
	{code: 'NE', name: 'Niger'},
	{code: 'NG', name: 'Nigeria'},
	{code: 'NU', name: 'Niue'},
	{code: 'NF', name: 'Norfolk Island'},
	{code: 'MP', name: 'Northern Mariana Islands'},
	{code: 'NO', name: 'Norway'},
	{code: 'OM', name: 'Oman'},
	{code: 'PK', name: 'Pakistan'},
	{code: 'PW', name: 'Palau'},
	{code: 'PS', name: 'Palestinian Territory, Occupied'},
	{code: 'PA', name: 'Panama'},
	{code: 'PG', name: 'Papua New Guinea'},
	{code: 'PY', name: 'Paraguay'},
	{code: 'PE', name: 'Peru'},
	{code: 'PH', name: 'Philippines'},
	{code: 'PN', name: 'Pitcairn'},
	{code: 'PL', name: 'Poland'},
	{code: 'PT', name: 'Portugal'},
	{code: 'PR', name: 'Puerto Rico'},
	{code: 'QA', name: 'Qatar'},
	{code: 'RE', name: 'Reunion'},
	{code: 'RO', name: 'Romania'},
	{code: 'RU', name: 'Russian Federation'},
	{code: 'RW', name: 'Rwanda'},
	{code: 'SH', name: 'Saint Helena'},
	{code: 'KN', name: 'Saint Kitts and Nevis'},
	{code: 'LC', name: 'Saint Lucia'},
	{code: 'PM', name: 'Saint Pierre and Miquelon'},
	{code: 'VC', name: 'Saint Vincent and The Grenadines'},
	{code: 'WS', name: 'Samoa'},
	{code: 'SM', name: 'San Marino'},
	{code: 'ST', name: 'Sao Tome and Principe'},
	{code: 'SA', name: 'Saudi Arabia'},
	{code: 'SN', name: 'Senegal'},
	{code: 'RS', name: 'Serbia'},
	{code: 'SC', name: 'Seychelles'},
	{code: 'SL', name: 'Sierra Leone'},
	{code: 'SG', name: 'Singapore'},
	{code: 'SK', name: 'Slovakia'},
	{code: 'SI', name: 'Slovenia'},
	{code: 'SB', name: 'Solomon Islands'},
	{code: 'SO', name: 'Somalia'},
	{code: 'ZA', name: 'South Africa'},
	{code: 'GS', name: 'South Georgia and The South Sandwich Islands'},
	{code: 'ES', name: 'Spain'},
	{code: 'LK', name: 'Sri Lanka'},
	{code: 'SD', name: 'Sudan'},
	{code: 'SR', name: 'Suriname'},
	{code: 'SJ', name: 'Svalbard and Jan Mayen'},
	{code: 'SZ', name: 'Swaziland'},
	{code: 'SE', name: 'Sweden'},
	{code: 'CH', name: 'Switzerland'},
	{code: 'SY', name: 'Syrian Arab Republic'},
	{code: 'TW', name: 'Taiwan, Province of China'},
	{code: 'TJ', name: 'Tajikistan'},
	{code: 'TZ', name: 'Tanzania, United Republic of'},
	{code: 'TH', name: 'Thailand'},
	{code: 'TL', name: 'Timor-leste'},
	{code: 'TG', name: 'Togo'},
	{code: 'TK', name: 'Tokelau'},
	{code: 'TO', name: 'Tonga'},
	{code: 'TT', name: 'Trinidad and Tobago'},
	{code: 'TN', name: 'Tunisia'},
	{code: 'TR', name: 'Turkey'},
	{code: 'TM', name: 'Turkmenistan'},
	{code: 'TC', name: 'Turks and Caicos Islands'},
	{code: 'TV', name: 'Tuvalu'},
	{code: 'UG', name: 'Uganda'},
	{code: 'UA', name: 'Ukraine'},
	{code: 'AE', name: 'United Arab Emirates'},
	{code: 'GB', name: 'United Kingdom'},
	{code: 'US', name: 'United States'},
	{code: 'UM', name: 'United States Minor Outlying Islands'},
	{code: 'UY', name: 'Uruguay'},
	{code: 'UZ', name: 'Uzbekistan'},
	{code: 'VU', name: 'Vanuatu'},
	{code: 'VE', name: 'Venezuela'},
	{code: 'VN', name: 'Viet Nam'},
	{code: 'VG', name: 'Virgin Islands, British'},
	{code: 'VI', name: 'Virgin Islands, U.S.'},
	{code: 'WF', name: 'Wallis and Futuna'},
	{code: 'EH', name: 'Western Sahara'},
	{code: 'YE', name: 'Yemen'},
	{code: 'ZM', name: 'Zambia'},
	{code: 'ZW', name: 'Zimbabwe'},
];